# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../../../ui/MainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PoemStudioWin(object):
    def setupUi(self, PoemStudioWin):
        PoemStudioWin.setObjectName("PoemStudioWin")
        PoemStudioWin.resize(771, 542)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../ui\\../photos/b.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PoemStudioWin.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(PoemStudioWin)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(80, 140, 651, 271))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.Buttons = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.Buttons.setContentsMargins(0, 0, 0, 0)
        self.Buttons.setObjectName("Buttons")
        self.FindPoem = QtWidgets.QCommandLinkButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.FindPoem.setFont(font)
        self.FindPoem.setText("     古   诗   查   找")
        self.FindPoem.setObjectName("FindPoem")
        self.Buttons.addWidget(self.FindPoem)
        self.Game = QtWidgets.QCommandLinkButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.Game.setFont(font)
        self.Game.setText("     古   诗   答   题")
        self.Game.setObjectName("Game")
        self.Buttons.addWidget(self.Game)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 40, 651, 71))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(430, 410, 321, 101))
        self.label_4.setStyleSheet("font: 25 9pt \"Microsoft YaHei UI Light\";\n"
"color: rgb(177, 177, 177);")
        self.label_4.setObjectName("label_4")
        PoemStudioWin.setCentralWidget(self.centralwidget)
        self.Tools = QtWidgets.QMenuBar(PoemStudioWin)
        self.Tools.setGeometry(QtCore.QRect(0, 0, 771, 30))
        self.Tools.setObjectName("Tools")
        self.Func = QtWidgets.QMenu(self.Tools)
        self.Func.setObjectName("Func")
        self.Help = QtWidgets.QMenu(self.Tools)
        self.Help.setObjectName("Help")
        PoemStudioWin.setMenuBar(self.Tools)
        self.act_FindPoem = QtWidgets.QAction(PoemStudioWin)
        self.act_FindPoem.setObjectName("act_FindPoem")
        self.act_Game = QtWidgets.QAction(PoemStudioWin)
        self.act_Game.setObjectName("act_Game")
        self.act_About = QtWidgets.QAction(PoemStudioWin)
        self.act_About.setObjectName("act_About")
        self.act_Help = QtWidgets.QAction(PoemStudioWin)
        self.act_Help.setObjectName("act_Help")
        self.act_Quit = QtWidgets.QAction(PoemStudioWin)
        self.act_Quit.setObjectName("act_Quit")
        self.Func.addAction(self.act_FindPoem)
        self.Func.addSeparator()
        self.Func.addAction(self.act_Game)
        self.Help.addAction(self.act_About)
        self.Help.addAction(self.act_Help)
        self.Help.addSeparator()
        self.Help.addAction(self.act_Quit)
        self.Tools.addAction(self.Func.menuAction())
        self.Tools.addAction(self.Help.menuAction())

        self.retranslateUi(PoemStudioWin)
        self.act_Quit.triggered.connect(PoemStudioWin.close)
        QtCore.QMetaObject.connectSlotsByName(PoemStudioWin)

    def retranslateUi(self, PoemStudioWin):
        _translate = QtCore.QCoreApplication.translate
        PoemStudioWin.setWindowTitle(_translate("PoemStudioWin", "PoemStudio"))
        self.label.setText(_translate("PoemStudioWin", "Welcome to PoemStudio!"))
        self.label_4.setText(_translate("PoemStudioWin", "特别鸣谢:古诗文网 gushiwen.org"))
        self.Func.setTitle(_translate("PoemStudioWin", "功能(&T)"))
        self.Help.setTitle(_translate("PoemStudioWin", "帮助(&H)"))
        self.act_FindPoem.setText(_translate("PoemStudioWin", "古诗查找(&F)"))
        self.act_FindPoem.setShortcut(_translate("PoemStudioWin", "Ctrl+F"))
        self.act_Game.setText(_translate("PoemStudioWin", "古诗答题(&G)"))
        self.act_Game.setShortcut(_translate("PoemStudioWin", "Ctrl+G"))
        self.act_About.setText(_translate("PoemStudioWin", "关于PoemStudio...(&A)"))
        self.act_About.setShortcut(_translate("PoemStudioWin", "Ctrl+A"))
        self.act_Help.setText(_translate("PoemStudioWin", "帮助(&U)"))
        self.act_Help.setShortcut(_translate("PoemStudioWin", "F1"))
        self.act_Quit.setText(_translate("PoemStudioWin", "退出(&Q)"))
        self.act_Quit.setShortcut(_translate("PoemStudioWin", "Ctrl+Q"))
