# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../../../ui/PoemGame.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PoemGame(object):
    def setupUi(self, PoemGame):
        PoemGame.setObjectName("PoemGame")
        PoemGame.resize(800, 600)
        PoemGame.setMinimumSize(QtCore.QSize(800, 600))
        PoemGame.setMaximumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../ui\\../photos/b.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PoemGame.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(PoemGame)
        self.centralwidget.setObjectName("centralwidget")
        self.choose = QtWidgets.QPushButton(self.centralwidget)
        self.choose.setGeometry(QtCore.QRect(640, 60, 141, 41))
        self.choose.setStyleSheet("font: 25 9pt \"Microsoft YaHei UI Light\";")
        self.choose.setCheckable(True)
        self.choose.setObjectName("choose")
        self.restart = QtWidgets.QPushButton(self.centralwidget)
        self.restart.setGeometry(QtCore.QRect(490, 470, 131, 41))
        self.restart.setStyleSheet("font: 25 9pt \"Microsoft YaHei UI Light\";")
        self.restart.setObjectName("restart")
        self.next = QtWidgets.QPushButton(self.centralwidget)
        self.next.setGeometry(QtCore.QRect(640, 470, 131, 41))
        self.next.setStyleSheet("font: 25 9pt \"Microsoft YaHei UI Light\";")
        self.next.setObjectName("next")
        self.CA = QtWidgets.QRadioButton(self.centralwidget)
        self.CA.setGeometry(QtCore.QRect(60, 330, 731, 31))
        self.CA.setStyleSheet("font: 25 9pt \"Microsoft YaHei UI Light\";")
        self.CA.setObjectName("CA")
        self.CC = QtWidgets.QRadioButton(self.centralwidget)
        self.CC.setGeometry(QtCore.QRect(60, 450, 731, 31))
        self.CC.setStyleSheet("font: 25 9pt \"Microsoft YaHei UI Light\";")
        self.CC.setObjectName("CC")
        self.CB = QtWidgets.QRadioButton(self.centralwidget)
        self.CB.setGeometry(QtCore.QRect(60, 390, 731, 31))
        self.CB.setStyleSheet("font: 25 9pt \"Microsoft YaHei UI Light\";")
        self.CB.setObjectName("CB")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(20, 50, 591, 51))
        self.title.setStyleSheet("font: 25 9pt \"Microsoft YaHei UI Light\";")
        self.title.setObjectName("title")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(600, 540, 191, 31))
        self.label.setStyleSheet("font: 25 9pt \"Microsoft YaHei UI Light\";")
        self.label.setObjectName("label")
        self.test = QtWidgets.QLabel(self.centralwidget)
        self.test.setGeometry(QtCore.QRect(20, 110, 751, 71))
        self.test.setStyleSheet("font: 25 9pt \"Microsoft YaHei UI Light\";")
        self.test.setObjectName("test")
        self.quit = QtWidgets.QPushButton(self.centralwidget)
        self.quit.setGeometry(QtCore.QRect(20, 530, 121, 51))
        self.quit.setObjectName("quit")
        PoemGame.setCentralWidget(self.centralwidget)

        self.retranslateUi(PoemGame)
        self.quit.clicked.connect(PoemGame.close)
        QtCore.QMetaObject.connectSlotsByName(PoemGame)

    def retranslateUi(self, PoemGame):
        _translate = QtCore.QCoreApplication.translate
        PoemGame.setWindowTitle(_translate("PoemGame", "古诗答题 - PoemStudio"))
        self.choose.setText(_translate("PoemGame", "选择"))
        self.choose.setShortcut(_translate("PoemGame", "Ctrl+C"))
        self.restart.setText(_translate("PoemGame", "重新开始"))
        self.restart.setShortcut(_translate("PoemGame", "Ctrl+R"))
        self.next.setText(_translate("PoemGame", "下一题"))
        self.next.setShortcut(_translate("PoemGame", "Ctrl+N"))
        self.CA.setText(_translate("PoemGame", "未选择"))
        self.CA.setShortcut(_translate("PoemGame", "1"))
        self.CC.setText(_translate("PoemGame", "未选择"))
        self.CC.setShortcut(_translate("PoemGame", "3"))
        self.CB.setText(_translate("PoemGame", "未选择"))
        self.CB.setShortcut(_translate("PoemGame", "2"))
        self.title.setText(_translate("PoemGame", "当前古诗："))
        self.label.setText(_translate("PoemGame", "正确率 0/0"))
        self.test.setText(_translate("PoemGame", "题目："))
        self.quit.setText(_translate("PoemGame", "退出"))
        self.quit.setShortcut(_translate("PoemGame", "Ctrl+Q"))
