# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../../../ui/ViewPoem.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ViewPoem(object):
    def setupUi(self, ViewPoem):
        ViewPoem.setObjectName("ViewPoem")
        ViewPoem.resize(791, 610)
        ViewPoem.setMinimumSize(QtCore.QSize(791, 610))
        ViewPoem.setMaximumSize(QtCore.QSize(791, 610))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../ui\\../photos/z.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ViewPoem.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(ViewPoem)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 791, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.l_title = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft Yi Baiti")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.l_title.setFont(font)
        self.l_title.setStyleSheet("font: 9pt \"Microsoft Yi Baiti\";")
        self.l_title.setObjectName("l_title")
        self.verticalLayout.addWidget(self.l_title)
        self.l_author = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.l_author.setMinimumSize(QtCore.QSize(789, 57))
        self.l_author.setStyleSheet("font: 9pt \"Microsoft Yi Baiti\";")
        self.l_author.setObjectName("l_author")
        self.verticalLayout.addWidget(self.l_author)
        self.ll = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.ll.setMaximumSize(QtCore.QSize(789, 57))
        self.ll.setStyleSheet("font: 9pt \"Microsoft Yi Baiti\";")
        self.ll.setObjectName("ll")
        self.verticalLayout.addWidget(self.ll)
        self.Show = QtWidgets.QTextEdit(self.centralwidget)
        self.Show.setGeometry(QtCore.QRect(0, 190, 791, 421))
        self.Show.setStyleSheet("font: 25 9pt \"Microsoft YaHei UI Light\";\n"
"background-color: rgb(255, 246, 226);")
        self.Show.setReadOnly(True)
        self.Show.setOverwriteMode(True)
        self.Show.setObjectName("Show")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(620, 150, 141, 34))
        self.pushButton.setStyleSheet("font: 9pt \"Microsoft Yi Baiti\";")
        self.pushButton.setObjectName("pushButton")
        ViewPoem.setCentralWidget(self.centralwidget)

        self.retranslateUi(ViewPoem)
        self.pushButton.clicked.connect(ViewPoem.close)
        QtCore.QMetaObject.connectSlotsByName(ViewPoem)

    def retranslateUi(self, ViewPoem):
        _translate = QtCore.QCoreApplication.translate
        ViewPoem.setWindowTitle(_translate("ViewPoem", "浏览古诗 - PoemStudio"))
        self.l_title.setText(_translate("ViewPoem", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">古诗名称:</span></p></body></html>"))
        self.l_author.setText(_translate("ViewPoem", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">古诗作者:</span></p></body></html>"))
        self.ll.setText(_translate("ViewPoem", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">原文:</span></p></body></html>"))
        self.pushButton.setToolTip(_translate("ViewPoem", "<html><head/><body><p>退出浏览古诗</p></body></html>"))
        self.pushButton.setText(_translate("ViewPoem", "退  出"))
        self.pushButton.setShortcut(_translate("ViewPoem", "Ctrl+Q"))
